feat: Adicionar campo para data de ultima atualização
gabrielfurlan-dev/weekly-report pull request #25
Opened 2023-08-26 16:43 UTC by GabrielGarcia190

Adicionei um campo que mostra há quanto tempo o report e a semana foram atualizadas, adicionei também teste de unidade para a função que realiza esta valição.

2023-08-27 02:40 UTC, gabrielfurlan-dev requested changes
Anotei algumas sugestões no PR.

OBS: Necessário adicionar data de tempo decorrido também nas metas de Check, não só nas de progresso.

2023-08-27 02:40 UTC, gabrielfurlan-dev commented on src/components/goals/ProgressGoal/ProgressGoal.tsx
> +                        <p className={`mt-2 text-lg text-[${completou}]`}>{goal.title}</p>
@GabrielGarcia190

O tailwind não consegue computar os elementos que estão em variáveis. 
Caso essa estilização não tenha sido computado em nenhum outro lugar anteriormente, ela não será aplicada.

Sugestões:
    1.  Utilizar a estilização dentro da propriedade _Style_ do próprio React;
    2.  (Melhor) Utilizar a biblioteca [tailwind-variants](https://www.tailwind-variants.org/) para realizar mudanças no estilo através de condicionais.
    
A segunda sugestão tem mais valor, pois podemos utiliza-lá em outros lugares que também tem esse problema, porém fica a seu critério.

2023-08-27 02:40 UTC, gabrielfurlan-dev commented on src/helpers/elapsedTime.ts
> +
Remover espaços em branco.

2023-08-27 02:40 UTC, gabrielfurlan-dev commented on src/helpers/elapsedTime.ts
### Sugestão:
**1.** Separar em 3 funções:
- getTimeElapsed;
- getCreatedTimeElapsed;
- getUpdatedTimeElapsed;

**ou**

**2.** Criar um parâmetro para determinar se a mensagem será para datas de criação ou de atualização.

2023-08-27 02:40 UTC, gabrielfurlan-dev commented on src/helpers/elapsedTime.ts
Alterar nome de variáveis/métodos para inglês a fim de seguir a padronização do sistema.

2023-08-27 02:40 UTC, gabrielfurlan-dev commented on src/helpers/elapsedTime.ts
> +            ? 'Criado agora'
**Sugestão**: Alterar de "Criado agora" para "Atualizado agora mesmo".

Para as datas de criação utilizar método separado ou adicionar parâmetro no método como sugerido anteriormente.

2023-08-27 02:40 UTC, gabrielfurlan-dev commented on test/tempUpdated.test.ts
> +    const currentDate = new Date();
Ao invés de instanciar várias variáveis para pegar a data atual, utilizar apenas uma e ir substituindo elas.

ex: 
```ts
   //Declaro a variavel
    const currentDate = new Date();
    currentDateTime.setMinutes(currentDateTime.getMinutes() - 30);
    result = elapsedTime(currentDateTime.toISOString());
    expect(result).toBe(`Atualizado há 30 minutos atrás`);

    //Apenas atualizo a variavel existente para a data atual
    currentDate = new Date();
    currentTimestamp.setSeconds(currentTimestamp.getSeconds() - 15);
    result = elapsedTime(currentTimestamp.toISOString());
    expect(result).toBe(`Atualizado há 15 segundos atrás`);
```

2023-08-29 01:19 UTC, GabrielGarcia190 commented
@gabrielfurlan-dev 

Adicionei algumas das sugestões e realizei as correções apontadas.

2023-08-29 22:21 UTC, GabrielGarcia190 commented on src/components/goals/ProgressGoal/ProgressGoal.tsx
> +                        <p className={`mt-2 text-lg text-[${completou}]`}>{goal.title}</p>
Não será viável implementar neste momento.

2023-08-29 22:23 UTC, gabrielfurlan-dev submitted a review, later dismissed

2023-08-30 02:43 UTC, gabrielfurlan-dev approved these changes

2023-08-30 02:45 UTC, merged