Corrigir data sendo apresentada com uma barra indevida
gabrielfurlan-dev/weekly-report pull request #34
Opened 2023-09-05 01:01 UTC by GabrielGarcia190

Durante o desenvolvimento inclui  uma função que formata a data para padroniza-la, facilitando assim o tratando dos dados. Desenvolvi duas funções que retornam um modelo diferentes de datas permitindo que os usuários visualizem a data corretamente de acordo com a linguagem de seu navegador.

2023-09-05 21:39 UTC, gabrielfurlan-dev requested changes

2023-09-05 21:50 UTC, GabrielGarcia190 commented on yarn.lock
> -  version "2.30.0"
Porque no projeto existiam duas bibliotecas parecidas, uma chamada date-fns-tz, esta foi removida

2023-09-06 02:26 UTC, gabrielfurlan-dev commented on yarn.lock
> -  version "2.30.0"
a que foi removida foi a date-fns, ela tem a ver com a tz ou nem?

2023-09-06 22:33 UTC, GabrielGarcia190 commented on src/helpers/dateHelper.ts
> +    const firstDayFormatted = `${interval.firstDayOfWeek.getDate().toString().padStart(2, '0')}/${(interval.firstDayOfWeek.getMonth() + 1).toString().padStart(2, '0')}`;
Porque os meses são um array de números iniciado em zero, exemplo:
Janeiro: 0
Fevereiro: 1
Março: 2
Por conta disto se faz necessário o +1 para que o usuário consiga visualizar corretamente os meses.

2023-09-06 22:45 UTC, GabrielGarcia190 commented on src/helpers/dateHelper.ts
> +    return `${month}-${month}-${day}`;
Realizei a correção solicitada

2023-09-07 00:06 UTC, GabrielGarcia190 commented on src/helpers/dateHelper.ts
> +    const firstDayFormatted = `${interval.firstDayOfWeek.getDate().toString().padStart(2, '0')}/${(interval.firstDayOfWeek.getMonth() + 1).toString().padStart(2, '0')}`;
As funções foram separadas no commit: [ff040f4](https://github.com/gabrielfurlan-dev/weekly-report/pull/34/commits/ff040f45cb39cf249c6c8eec23469a269004b96c)

2023-09-07 00:07 UTC, GabrielGarcia190 commented on yarn.lock
> -  version "2.30.0"
Sim, verifiquei e a biblioteca removida foi ai date-fns, então adicionei ela novamente

2023-09-07 13:58 UTC, gabrielfurlan-dev submitted a review, later dismissed

2023-09-07 14:25 UTC, gabrielfurlan-dev commented
## Necessário Revisão
Erro ao tentar acessar um Report.

### Passos para Reprodução
1. Acessar a tela de listar os Reports
2. Clicar para visualizar algum Report
3. ![image](https://github.com/gabrielfurlan-dev/weekly-report/assets/79483921/ffc0e4b8-c3da-44f9-bd79-3afda91e6164)

2023-10-12 18:33 UTC, gabrielfurlan-dev commented
Pull Request Aprovado.

2023-10-12 18:33 UTC, merged